image: 'node:8'

before_script:
  - apt-get -qq update
  - apt-get install -yq gconf-service
  - apt-get install -yq libasound2 libatk1.0-0 libc6 libcairo2
  - apt-get install -yq libcups2 libdbus-1-3 libexpat1 libfontconfig1
  - apt-get install -yq libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0
  - apt-get install -yq libglib2.0-0 libgtk-3-0 libnspr4
  - apt-get install -yq libpango-1.0-0 libpangocairo-1.0-0 libstdc++6
  - apt-get install -yq libx11-6 libx11-xcb1 libxcb1 libxcomposite1
  - apt-get install -yq libxcursor1 libxdamage1 libxext6 libxfixes3
  - apt-get install -yq libxi6 libxrandr2 libxrender1 libxss1 libxtst6
  - apt-get install -yq ca-certificates fonts-liberation
  - apt-get install -yq libappindicator1 libnss3 lsb-release xdg-utils
  - yarn install

stages:
  - test
  - build

test:
  script:
    - yarn run test

build:
  script:
    - yarn run build
